### ISSUE TITLE
本地文件没有进行筛选程序异常（已解决√）

### ISSUE THREAD

**Issue by BackMountainDevil** [NJU-TJL/Qt5-MusicPlayer#2]
假如不小心选错了文件，比如cpp文件（我早上试的），然后程序异常自动关闭了
可以在选取本地文件的代码里加入 
*mp3 

如我修改后的：
QUrl path =  QFileDialog::getOpenFileUrl(this,tr("请选择要播放的音乐"),QUrl( "C:/"),"music(*.mp3 *.wav )");

**Comment by NJU-TJL** [comment]
你好~ 感谢反馈！
不过，这个问题我刚刚测试的时候没有出现 ...
如下：
![show](https://user-images.githubusercontent.com/54802039/77060876-3f2c9d00-6a14-11ea-9bbe-0b855d685d7d.gif)
拖拽添加和文件选择框（选择框显示的是All File，所有文件都可以选择；我在标题栏写了一点提示：有：自动过滤... ）添加，其实都是使用的MusicList::addMusic这个函数来添加歌曲，而在其中我是做了文件过滤的。
当初做文件过滤，也是为了方便使用，因为这里支持歌词文件.lrc，要放在歌曲文件同目录下，所以这里预期是直接全选文件，就能直接添加，所以做了过滤。
起初也是想你说的这样使用文件后缀名过滤，后来改成了用Qt提供的一些函数来做，就是对url的类型与可播放类型进行对比，具体的实现可以参考以下代码：
```c++
... ....
//在Music.cpp文件中
void MusicList::addMusic(const QList<QUrl> &urls)
{
    //实测这里耗时较长，所以添加一个进度显示对话框
    QProgressDialog proDialog(u8"添加进度",u8"取消",0,urls.size());
    proDialog.setMinimumSize(350,150);
    proDialog.setWindowModality(Qt::WindowModal);
    proDialog.setWindowTitle("添加中...请稍后");
    proDialog.show();
    int x=0;
    foreach (QUrl i, urls) {
        x++;
        proDialog.setValue(x);
        //过滤Url的类型
        QMimeDatabase db;
        QMimeType mime = db.mimeTypeForFile(i.toLocalFile());
        if(mime.name()!="audio/mpeg"&&mime.name()!="audio/flac"){
            continue;
        }
        //剩下的符合类型
        music.push_back(Music(i));
        if(sql_flag){
            music[music.size()-1].insertSQL(name);
        }
        if(proDialog.wasCanceled()) break;
    }
}
```

PS：这个项目是临近期末的一个课程设计，当时大概花了一两周的时间做，而且代码量确实很大，所以确实存在很多Bug，希望大家见谅！




> 假如不小心选错了文件，比如cpp文件（我早上试的），然后程序异常自动关闭了
> 可以在选取本地文件的代码里加入
> *mp3
> 
> 如我修改后的：
> QUrl path = QFileDialog::getOpenFileUrl(this,tr("请选择要播放的音乐"),QUrl( "C:/"),"music(*.mp3 *.wav )");

**Comment by BackMountainDevil** [comment]
对，就在在学你这个文件筛选我看了一天。。。最后才搞懂。我采用了和你修改后的方案使用在MiniMusicPlayer 2.0中。我当时用你的课设放flac结果程序异常结束了。。。。两周！！！我去，太强了吧，要结合数据库和Qt。。。。。Qsql一言难尽。。。还在学习，向大佬致敬

**Comment by NJU-TJL** [comment]
hhh 不敢当~/抱拳！🤝 😀
QSql我这里使用了一点点（可以在代码中搜一下）用来存储歌单信息 写好了接口之后，后面我就仅仅是调用一下，也没深入研究~😂

对啦，这个Issue，我Reopen可以吗？便于遇到同样问题的Coder参考...
如果你介意的话，那就麻烦你自己再关闭一次啦~

**Comment by 1360307811** [comment]
你好 为什么我添加歌曲时无法加入

**Comment by NJU-TJL** [comment]
> 你好 为什么我添加歌曲时无法加入

为了排除歌曲文件的问题，你可以试试我提供的这个几个文件。（全选后拖拽进播放器界面即可添加）
链接：https://pan.baidu.com/s/1TKjo_Z0501c7NYwYsc9bVg 
提取码：kt0n

**Comment by 1360307811** [comment]
你好 你的音乐可以 谢谢

**Comment by NJU-TJL** [comment]
> 你好 你的音乐可以 谢谢

好的 不客气~ 祝开发愉快！
