### ISSUE TITLE
Player somehow was installed on my PC

### ISSUE THREAD

**Issue by UsievaladHaponienka** [NJU-TJL/Qt5-MusicPlayer#8]
Hello! Somehow your player was installed on my PC) This is weird, because I didn't install it by myself- but I'm sure that's it, it's called `LightMusicPlayer by NJU-TJL` and it also looks excatly like player at screenshots in your README. 

The other weird thing - it behaves like a virus: it's not displayed in autoload list and in programms list. I deleted it using Revo Uninstaller - but that didn't help, it "returns" after couple of days.

Files are located in folder C:/ProgrammData/CaphZone-e5b6b7a5-3064-46ba-a449-f31288f8eb69. 

Could you, please, help me with deleting it? With all respect to your work, but I don't need it) Thanks in advance!

**Comment by EricAwesomeDude** [comment]
I've got the same issue, have you found out a way to uninstall it?

**Comment by UsievaladHaponienka** [comment]
Nope. I think, reinstalling OS might help, but I don't want to take such brutal steps)

**Comment by NJU-TJL** [comment]
Sorry for what happened to you, but this software has no installation behavior, only an EXE file. I guess that there may be malicious people using this EXE program to create related viruses. I can't provide an uninstallation method, please try to use some security guard software to deal with it, good luck!
